### ISSUE TITLE
Convert paper records /w OCR & AI

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.OCR#1]
# Description
Make a service to convert paper records to data in the system

# Tasks
* [x] Crop tables from image of record
* [x] Crop table cells from the table to score raw data
* [x] Number recognition from the score raw data to structured output date

# Note
* May require etases/EduBlock.RS#32 to finish
